### ISSUE TITLE
Colon in @name annotation

### ISSUE THREAD

**Issue by szgabsz91** [eslint/doctrine#146] opened 2016-01-19 15:41 UTC
Hi,

I have an AngularJS application with code similar to this:

    /**
     * @ngdoc service
     * @name com.something.service:MyService
     */
    function MyService() {
    }

When executing the `valid-jsdoc` rule of eslint, the above code throws an error because that colon character causes trouble while processing the line of `@name`.

This colon makes it possible to categorize different AngularJS objects into different categories like service, directive, controller, so I think this should be supported by doctrine even if the `valid-jsdoc` rule does not target ngdoc specifically.

I found a one-liner change that affects the condition of doctrine.js line 334, so if you agree with me, I could create a pull request as well. (Although I haven't tested with trunk yet, but I guess it will be the same.)

Thanks in advance.

**Comment by nzakas** [comment] 2016-01-19 16:22
Duplicate of https://github.com/eslint/doctrine/issues/116

**Closed by nzakas** 2016-01-19 16:22 UTC
